# Site settings
title: "Resume Prabhdeep Singh"
description: "A resume to describe Prabhdeep's ability."

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "PRABHDEEP SINGH"
resume_title:                   "Full Stack Java Developer"

# used for the contact button in _layouts/resume.html
resume_contact_email:           "prabhdeep_singh17@yahoo.com"

# the next two items are used for schema itemprops in _layouts/resume.html
resume_contact_telephone:       "519-991-7179"
resume_contact_address:         "44 Fern Valley Crescent, Brampton, Ontario, Canada, L6R 1K6"

resume_header_contact_info:     "44 Fern Valley Crescent, Brampton, Ontario, Canada, L6R 1K6 • 519-991-7179 • prabhdeep_singh17@yahoo.com"
display_header_contact_info:    "false"

resume_header_intro: "<p>Result-oriented and capable Full Stack Java Developer with an extensive experience in creating, designing dynamic and beautiful cross-browser compatible web applications
,corporate websites and optimizing them for maximum speed and usability by using OOD, RWD and Cross-browser Compatibility. Good understanding of AGILE SDLC methodologies, TDD, Iteration planning, Pair Programming.
Ability to work independently or in a part of team with high efficiency.</p>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
resume_section_projects:        true
resume_section_skills:          true
resume_section_recognition:     true
#resume_section_links:           true
resume_section_associations:    true
#resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/Prabhdeep1994"
  resume_linkedin_url:          "https://www.linkedin.com/in/prabhdeep-singh-144463157/"
  
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
